language: android
jdk: oraclejdk7
android:
    components:
        - build-tools-22
        - android-22
        - extra-android-support
        - extra-android-m2repository

script:
- ./gradlew clean build
